The github issue for the bug is: https://github.com/pytest-dev/pytest-asyncio/issues/1083
